FROM openjdk:8u201-jdk-alpine
VOLUME /tmp                
EXPOSE 8000                
ADD target/schoolmanagement.jar schoolmanagement.jar 
ENTRYPOINT ["java","-jar","/schoolmanagement.jar"]  








