FROM openjdk:8               
EXPOSE 8000                   
ADD target/schoolmanagement-0.0.1-SNAPSHOT.jar schoolmanagement-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java","-jar","/schoolmanagement-0.0.1-SNAPSHOT.jar"]             




