server.servlet.context-path=/schoolmanagement
server.port=8000

#Spring Boot Database Connection -Start
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=Fakhrudeen77
spring.datasource.password=Shafana77
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true
#Spring Boot Database Connection -Start

# JWT Secret Key
jwt.secret=VGhpc0lzTXlTdXBlclNlY3JldEtleUZvckpXVFRva2VuMTIzNDU2Nzg5MA==
# Access Token Expiration (15 minutes)
jwt.expiration=900000
# Refresh Token Expiration (7 Days)
jwt.refresh-expiration=604800000
vt
# Spring Boot Actuator Configuration - Start
# Enable all endpoints to be accessed (bypassing the security)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# Spring Boot Actuator Configuration - Emd

#Spring Boot Connection Pool HikariCP Pool Size  -Start
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
#Spring Boot Connection Pool HikariCP Pool Size  -End


#Spring Boot  logging level- Start
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG
logging.pattern.console=%c-[%level]- %d-%m-%n
logging.file.name=D:/school/schoolmgmt.txt
logging.pattern.file=%c-[%level]- %d-%m-%n
logging.level.org.springframework.security=DEBUG
#Spring Boot  logging level- End
